#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msm
Version  : 0.5.19
Release  : 1
URL      : https://files.pythonhosted.org/packages/ee/ee/8e1dd6ceefea93e2c7009ad7d9b2fb9fcfacad8321042611a4f1179f3e86/msm-0.5.19.tar.gz
Source0  : https://files.pythonhosted.org/packages/ee/ee/8e1dd6ceefea93e2c7009ad7d9b2fb9fcfacad8321042611a4f1179f3e86/msm-0.5.19.tar.gz
Summary  : Mycroft Skills Manager
Group    : Development/Tools
License  : Apache-2.0
Requires: msm-bin = %{version}-%{release}
Requires: msm-license = %{version}-%{release}
Requires: msm-python = %{version}-%{release}
Requires: msm-python3 = %{version}-%{release}
Requires: GitPython
Requires: typing
BuildRequires : GitPython
BuildRequires : buildreq-distutils3
BuildRequires : typing

%description
No detailed description available

%package bin
Summary: bin components for the msm package.
Group: Binaries
Requires: msm-license = %{version}-%{release}

%description bin
bin components for the msm package.


%package license
Summary: license components for the msm package.
Group: Default

%description license
license components for the msm package.


%package python
Summary: python components for the msm package.
Group: Default
Requires: msm-python3 = %{version}-%{release}

%description python
python components for the msm package.


%package python3
Summary: python3 components for the msm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the msm package.


%prep
%setup -q -n msm-0.5.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541254626
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/msm
cp LICENSE %{buildroot}/usr/share/package-licenses/msm/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/msm/LICENSE

%files bin
%defattr(-,root,root,-)
/usr/bin/msm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/msm/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
