#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msm
Version  : 0.7.6
Release  : 13
URL      : https://files.pythonhosted.org/packages/42/bb/af8b811e80a0f8f2dbc1b843fc89cade2c07c148a5b44fef2904210066e9/msm-0.7.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/42/bb/af8b811e80a0f8f2dbc1b843fc89cade2c07c148a5b44fef2904210066e9/msm-0.7.6.tar.gz
Summary  : Mycroft Skills Manager
Group    : Development/Tools
License  : Apache-2.0
Requires: msm-bin = %{version}-%{release}
Requires: msm-license = %{version}-%{release}
Requires: msm-python = %{version}-%{release}
Requires: msm-python3 = %{version}-%{release}
Requires: GitPython
Requires: PyYAML
Requires: fasteners
Requires: lazy
Requires: pako
Requires: typing
BuildRequires : GitPython
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : fasteners
BuildRequires : lazy
BuildRequires : pako
BuildRequires : typing

%description
No detailed description available

%package bin
Summary: bin components for the msm package.
Group: Binaries
Requires: msm-license = %{version}-%{release}

%description bin
bin components for the msm package.


%package license
Summary: license components for the msm package.
Group: Default

%description license
license components for the msm package.


%package python
Summary: python components for the msm package.
Group: Default
Requires: msm-python3 = %{version}-%{release}

%description python
python components for the msm package.


%package python3
Summary: python3 components for the msm package.
Group: Default
Requires: python3-core

%description python3
python3 components for the msm package.


%prep
%setup -q -n msm-0.7.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558645016
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/msm
cp LICENSE %{buildroot}/usr/share/package-licenses/msm/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/msm/LICENSE

%files bin
%defattr(-,root,root,-)
/usr/bin/msm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/msm/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
